[package]
name = "alliance_treasury"
edition = "2024"

[dependencies]
World = { git = "https://github.com/evefrontier/world-contracts.git", subdir = "contracts/world", rev = "v0.0.14" }

[addresses]
alliance_treasury = "0x0"
